//inequalities
let str1="ahmed"
let str2="afsha"
console.log(str1==str2)
console.log(str1!=str2)
//lowercase
let a:string='HELLOWORLD'
console.log(a.toLowerCase()=='helloworld')
//numerical testing
let b=1, c=2, d=3
console.log( c==b )
console.log(c!=b)
console.log(c<b)
console.log(c>b)
console.log(c<=b)
console.log(c>=b)
// and and or
console.log(c>b && c>d )
console.log(c>b  || c>d )
//item test
let u=[1,2,3,4,5]
console.log(u.includes(3))
//not in array
console.log(!u.includes(6))
