
//let names = ['Ammar', 'salma', 'Hafsa', 'Ammara']
let message = " 'you are invited to dinner'"
//console.log(names[0] + message);
//console.log(names[1] + message)
//console.log(names[2] + message)
//console.log(names[3] + message)

console.log("salma")//can't make to dinner

let names:string[]=['AMMAR','AMMARA','HAFSA']
let quantity: number = names.push('NAILA')

console.log(names[0] + message)
console.log(names[1] + message)
console.log(names[2] + message)
console.log(names[3] + message)